## simple RNN
- dataset : https://www.kaggle.com/datasets/iveeaten3223times/massive-yahoo-finance-dataset
- 연속형(=시계열, 문장 등) 데이터 처리에 유리

## 데이터 관련

In [1]:
# 데이터 로드
import pandas as pd
# df_stock = pd.read_csv('/kaggle/input/massive-yahoo-finance-dataset/stock_details_5_years.csv')
# df_stock.head(3)

df_stock_all = pd.read_csv('/kaggle/input/massive-yahoo-finance-dataset/stock_details_5_years.csv')
df_stock_all.head(3)

Date        Open        High         Low       Close  \
0  2018-11-29 00:00:00-05:00   43.829761   43.863354   42.639594   43.083508   
1  2018-11-29 00:00:00-05:00  104.769074  105.519257  103.534595  104.636131   
2  2018-11-29 00:00:00-05:00   54.176498   55.007500   54.099998   54.729000   

      Volume  Dividends  Stock Splits Company  
0  167080000        0.0           0.0    AAPL  
1   28123200        0.0           0.0    MSFT  
2   31004000        0.0           0.0   GOOGL

In [2]:
# 특정 회사(컴퍼니)만 시계열 가져오기 (나오게)
selected_company = 'AAPL'
df_stock = df_stock_all[df_stock_all['Company'] == selected_company]
df_stock.head()

Date       Open       High        Low      Close  \
0     2018-11-29 00:00:00-05:00  43.829761  43.863354  42.639594  43.083508   
458   2018-11-30 00:00:00-05:00  43.261071  43.270671  42.478826  42.850754   
916   2018-12-03 00:00:00-05:00  44.261681  44.376858  43.481835  44.348064   
1374  2018-12-04 00:00:00-05:00  43.419445  43.764977  42.296468  42.397247   
1832  2018-12-06 00:00:00-05:00  41.214280  41.938938  40.892744  41.924541   

         Volume  Dividends  Stock Splits Company  
0     167080000        0.0           0.0    AAPL  
458   158126000        0.0           0.0    AAPL  
916   163210000        0.0           0.0    AAPL  
1374  165377200        0.0           0.0    AAPL  
1832  172393600        0.0           0.0    AAPL

### 데이터 전처리

In [3]:
# 날짜를 datetime 변환
df_stock['Date'] = pd.to_datetime(df_stock['Date'], utc=True)
df_stock['Date'].dtype

<ipython-input-3-6faa62f0cc68>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock['Date'] = pd.to_datetime(df_stock['Date'], utc=True)


datetime64[ns, UTC]

In [4]:
# df_stock.info()

In [5]:
# 스케일링
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_stock[['Open','High','Low','Close','Volume']] = scaler.fit_transform(df_stock[['Open','High','Low','Close','Volume']])
df_stock.head(3)

<ipython-input-5-7eb35ecb155c>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stock[['Open','High','Low','Close','Volume']] = scaler.fit_transform(df_stock[['Open','High','Low','Close','Volume']])


Date      Open      High       Low     Close  \
0   2018-11-29 05:00:00+00:00 -1.598199 -1.611253 -1.611061 -1.615618   
458 2018-11-30 05:00:00+00:00 -1.610310 -1.623753 -1.614516 -1.620572   
916 2018-12-03 05:00:00+00:00 -1.589000 -1.600423 -1.592958 -1.588704   

       Volume  Dividends  Stock Splits Company  
0    1.176835        0.0           0.0    AAPL  
458  1.010309        0.0           0.0    AAPL  
916  1.104861        0.0           0.0    AAPL

In [6]:
df_stock.shape

(1258, 9)

In [7]:
# 시계열 데이터 생성
import numpy as np
import torch

sequence_length = 5 # 5일 단위

from tqdm import tqdm


def create_sequences(data, seq_length):
    xs = []
    ys = []
    # for i in range(len(data) - seq_length):
    for i in tqdm(range(len(data) - seq_length), desc = 'Generating Sequences'):
        x = data[i:i+seq_length]
        y = data[i+seq_length]
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys) # features, label

features, label = create_sequences(df_stock['Close'].values, sequence_length)
features.shape, label.shape

Generating Sequences: 100%|██████████| 1253/1253 [00:00<00:00, 1323127.62it/s]


((1253, 5), (1253,))

In [8]:
features[:3]

array([[-1.61561817, -1.62057201, -1.58870387, -1.63022425, -1.64028513],
       [-1.62057201, -1.58870387, -1.63022425, -1.64028513, -1.67210203],
       [-1.58870387, -1.63022425, -1.64028513, -1.67210203, -1.66643324]])

In [9]:
# 텐서 변환
features_tensor = torch.tensor(features, dtype = torch.float32).unsqueeze(-1)
label_tensor = torch.tensor(label, dtype = torch.float32).unsqueeze(-1)
features_tensor.shape, label_tensor.shape

(torch.Size([1253, 5, 1]), torch.Size([1253, 1]))

## 모델관련

In [10]:
# RNN 모델 정의
import torch.nn as nn

class SimpleRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleRNN, self).__init__()
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        h0 = torch.zeros(1, x.size(0), hidden_size)
        out, _ = self.rnn(x, h0)
        out = self.fc(out[:, -1, :])
        return out

input_size = 1 # row 단위 갯수
hidden_size = 5 # 은닉층 갯수
output_size = 1 

model = SimpleRNN(input_size, hidden_size, output_size)
model

SimpleRNN(
  (rnn): RNN(1, 5, batch_first=True)
  (fc): Linear(in_features=5, out_features=1, bias=True)
)

In [11]:
# 모델 학습
import torch.optim as optim

criterion = nn.MSELoss()
optimizer = optim.AdamW(model.parameters(), lr = 0.01)

epochs = 100

for epoch in tqdm(range(epochs), desc = 'learning Model'):
    model.train()
    outputs = model(features_tensor)
    optimizer.zero_grad()
    loss = criterion(outputs, label_tensor) # error율 확인
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0: # 10회에 1번 출력
        print(f'Epoch [{epoch+1} / {epochs}]. Loss : {loss.item():.5f}')

learning Model:  81%|████████  | 81/100 [00:00<00:00, 248.42it/s]

Epoch [10 / 100]. Loss : 0.75484
Epoch [20 / 100]. Loss : 0.38755
Epoch [30 / 100]. Loss : 0.05493
Epoch [40 / 100]. Loss : 0.05256
Epoch [50 / 100]. Loss : 0.02888
Epoch [60 / 100]. Loss : 0.02177
Epoch [70 / 100]. Loss : 0.01721
Epoch [80 / 100]. Loss : 0.01491
Epoch [90 / 100]. Loss : 0.01241


learning Model: 100%|██████████| 100/100 [00:00<00:00, 215.71it/s]

Epoch [100 / 100]. Loss : 0.01095


In [12]:
model.state_dict()

OrderedDict([('rnn.weight_ih_l0',
              tensor([[-0.3730],
                      [ 0.0368],
                      [ 0.1746],
                      [-0.4556],
                      [-0.5008]])),
             ('rnn.weight_hh_l0',
              tensor([[ 0.1839,  0.2416,  0.0006,  0.3604,  0.1347],
                      [-0.0115, -0.0886, -0.3826,  0.2802,  0.3423],
                      [-0.4097,  0.0032, -0.2343, -0.0299,  0.3455],
                      [ 0.3106, -0.3605, -0.0803, -0.0486,  0.1144],
                      [-0.1968, -0.4716,  0.1403,  0.1910,  0.2999]])),
             ('rnn.bias_ih_l0',
              tensor([-0.3379,  0.0077, -0.5455,  0.2126,  0.2498])),
             ('rnn.bias_hh_l0',
              tensor([ 0.2935,  0.2868,  0.1044, -0.1761, -0.1293])),
             ('fc.weight',
              tensor([[-0.6317, -0.1506,  0.1115, -0.6099, -0.5353]])),
             ('fc.bias', tensor([-0.0366]))])

## 평가 관련

In [13]:
model.eval()

SimpleRNN(
  (rnn): RNN(1, 5, batch_first=True)
  (fc): Linear(in_features=5, out_features=1, bias=True)
)

In [14]:
with torch.no_grad():
    predicted = model(features_tensor[:5])
predicted, label_tensor[:5]

(tensor([[-1.4909],
         [-1.5040],
         [-1.5047],
         [-1.5057],
         [-1.5052]]),
 tensor([[-1.6721],
         [-1.6664],
         [-1.6714],
         [-1.6690],
         [-1.6595]]))